name: Build Java with Node image

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        required: true
        type: string
      NODE_VERSION:
        required: true
        type: string
      TAG:
        required: false
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate TAG
        if: ${{ inputs.TAG != '' }}
        run: |
          echo "TAG=${{ vars.DOCKERHUB_USERNAME }}/java-node:${{ inputs.TAG }}" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            JAVA_VERSION=${{ inputs.JAVA_VERSION }}
            NODE_VERSION=${{ inputs.NODE_VERSION }}
          cache-from: type=gha,scope=java-${{ inputs.JAVA_VERSION }}
          cache-to: type=gha,scope=java-${{ inputs.JAVA_VERSION }},mode=max
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/java-node:java-${{ inputs.JAVA_VERSION }}-node-${{ inputs.NODE_VERSION }}
            ${{ env.TAG }}
