name: Build Java with Node LTS image

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
      node_version:
        required: true
        type: string

jobs:
  build-lts:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          file: lts/Dockerfile
          build-args: |
            JAVA_VERSION=${{ inputs.java_version }}
            NODE_VERSION=${{ inputs.node_version }}
          tags: dkmoonfruit/java-node:java-${{ inputs.java_version }}-node-${{ inputs.node_version }}
