name: Docker Image CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build java-8/node-10/Dockerfile
        id: docker_build_java_8_node_10
        uses: docker/build-push-action@v2
        with:
          push: true
          file: java-8/node-10/Dockerfile
          tags: dkmoonfruit/java-node:java-8-node-10

      - name: Build java-8/node-12/Dockerfile
        id: docker_build_java_8_node_12
        uses: docker/build-push-action@v2
        with:
          push: true
          file: java-8/node-12/Dockerfile
          tags: dkmoonfruit/java-node:java-8-node-12

      - name: Build java-8/node-14/Dockerfile
        id: docker_build_java_8_node_14
        uses: docker/build-push-action@v2
        with:
          push: true
          file: java-8/node-14/Dockerfile
          tags: dkmoonfruit/java-node:java-8-node-14
