name: Build Java with Node images

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: 0 0 1/15 * *
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      caches: ${{ steps.set-matrix.outputs.caches }}
      images: ${{ steps.set-matrix.outputs.images }}
    steps:
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Checkout
        uses: actions/checkout@v4
      - name: Preflight
        id: set-matrix
        run: |
          IMAGES=$(bin/preflight.sh)
          CACHES=$(echo "$IMAGES" | jq '. | {java}')
          bin/output.sh caches "$CACHES" >>$GITHUB_OUTPUT
          bin/output.sh images "$IMAGES" >>$GITHUB_OUTPUT
          cat "$GITHUB_OUTPUT"

  build-caches:
    needs: preflight
    strategy:
      matrix: ${{ fromJson(needs.preflight.outputs.caches) }}
    uses: ./.github/workflows/build-cache.yml
    with:
      JAVA_VERSION: ${{ matrix.java }}

  build-images:
    needs:
      - preflight
      - build-caches
    strategy:
      matrix: ${{ fromJson(needs.preflight.outputs.images) }}
    uses: ./.github/workflows/build-image.yml
    with:
      JAVA_VERSION: ${{ matrix.java }}
      NODE_VERSION: ${{ matrix.node }}
      TAG: ${{ matrix.tag }}
    secrets: inherit
