name: Build Java with Node images

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: 0 0 1/5 * *
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.preflight.outputs.build }}
      caches: ${{ steps.preflight.outputs.caches }}
      images: ${{ steps.preflight.outputs.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Preflight
        id: preflight
        run: |
          IMAGES=$(bin/preflight.sh)
          CACHES=$(echo "$IMAGES" | jq '. | {java}')
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes detected, skipping build."
            echo "build=false" >>$GITHUB_OUTPUT
          else
            echo "Changes detected, proceeding with build."
            echo "build=true" >>$GITHUB_OUTPUT
          fi
          bin/output.sh caches "$CACHES" >>$GITHUB_OUTPUT
          bin/output.sh images "$IMAGES" >>$GITHUB_OUTPUT
          cat "$GITHUB_OUTPUT"
      - name: Upload artifacts
        if: steps.preflight.outputs.build == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: preflight
          path: preflight
          retention-days: 1

  build-caches:
    needs: preflight
    if: needs.preflight.outputs.build == 'true'
    strategy:
      matrix: ${{ fromJson(needs.preflight.outputs.caches) }}
    uses: ./.github/workflows/build-cache.yml
    with:
      JAVA_VERSION: ${{ matrix.java }}

  build-images:
    needs:
      - preflight
      - build-caches
    if: needs.preflight.outputs.build == 'true'
    strategy:
      matrix: ${{ fromJson(needs.preflight.outputs.images) }}
    uses: ./.github/workflows/build-image.yml
    with:
      JAVA_VERSION: ${{ matrix.java }}
      NODE_VERSION: ${{ matrix.node }}
      TAG: ${{ matrix.tag }}
    secrets: inherit

  save-preflight:
    needs:
      - preflight
      - build-images
    if: needs.preflight.outputs.build == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: preflight
          path: preflight
      - name: Commit and Push
        run: |
          git add preflight
          git status
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Update preflight" && git push || echo "No changes to commit"
