name: Docker Image CI

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  java-8-node-10:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: java-8/node-10/Dockerfile
          tags: dkmoonfruit/java-node:java-8-node-10

  java-8-node-14:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: java-8/node-14/Dockerfile
          tags: dkmoonfruit/java-node:java-8-node-14

  java-8-node-16:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: java-8/node-16/Dockerfile
          tags: dkmoonfruit/java-node:java-8-node-16

  java-11-node-14:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: java-11/node-14/Dockerfile
          tags: |
            dkmoonfruit/java-node:java-11-node-14
            dkmoonfruit/java-node:lts

  java-11-node-16:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: java-11/node-16/Dockerfile
          tags: dkmoonfruit/java-node:java-11-node-16

  java-16-node-14:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: java-16/node-14/Dockerfile
          tags: dkmoonfruit/java-node:java-16-node-14

  java-16-node-16:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: java-16/node-16/Dockerfile
          tags: |
            dkmoonfruit/java-node:java-16-node-16
            dkmoonfruit/java-node:latest
