name: Build Java with Node images

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: 0 0 1/15 * *
  workflow_dispatch:

jobs:
  build-base-images:
    strategy:
      matrix:
        java-version: [8, 11, 17, 21, 23]
        node-version: [18]
    uses: ./.github/workflows/build-image.yml
    with:
      JAVA_VERSION: ${{ matrix.java-version }}
      NODE_VERSION: ${{ matrix.node-version }}
    secrets: inherit

  build-newer-images:
    needs: build-base-images
    strategy:
      matrix:
        java-version: [8, 11, 17, 21, 23]
        node-version: [20, 22]
        exclude:
          - java-version: 21
            node-version: 22
    uses: ./.github/workflows/build-image.yml
    with:
      JAVA_VERSION: ${{ matrix.java-version }}
      NODE_VERSION: ${{ matrix.node-version }}
    secrets: inherit

  build-lts-image:
    needs: build-base-images
    uses: ./.github/workflows/build-image.yml
    with:
      JAVA_VERSION: 21
      NODE_VERSION: 22
      TAG: lts
    secrets: inherit

  build-latest-image:
    needs: build-base-images
    uses: ./.github/workflows/build-image.yml
    with:
      JAVA_VERSION: 23
      NODE_VERSION: 23
      TAG: latest
    secrets: inherit
