name: Build Java with Node images

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: 0 0 1/15 * *
  workflow_dispatch:

jobs:
  build-image:
    strategy:
      matrix:
        java-version: [8, 11, 17, 21, 23]
        node-version: [18, 20, 22]
    uses: ../.github/workflows/build-image.yml
    with:
      JAVA_VERSION: ${{ matrix.java-version }}
      NODE_VERSION: ${{ matrix.node-version }}
    secrets: inherit

  build-latest-image:
    uses: ../.github/workflows/build-image.yml
    with:
      JAVA_VERSION: 23
      NODE_VERSION: 23
    secrets: inherit
