name: Docker Images CI

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: 0 0 1/15 * *
  workflow_dispatch:

jobs:
  build-lts:
    uses: ./.github/workflows/build-lts.yml
    strategy:
      matrix:
        java-version: [8, 11, 17, 21, 23]
        node-version: [18, 20, 22]
    with:
      JAVA_VERSION: ${{ matrix.java-version }}
      NODE_VERSION: ${{ matrix.node-version }}
    secrets: inherit

  # java-23-node-23:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #     - name: Build and Push
  #       id: docker_build
  #       uses: docker/build-push-action@v5
  #       with:
  #         push: true
  #         file: java-23/node-23/Dockerfile
  #         tags: |
  #           dkmoonfruit/java-node:java-23-node-23
  #           dkmoonfruit/java-node:latest
