name: Build Java with Node images

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: 0 0 1/15 * *
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      caches: ${{ steps.set-matrix.outputs.caches }}
      images: ${{ steps.set-matrix.outputs.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Preflight
        id: set-matrix
        run: |
          IMAGES=$(bin/preflight.sh)
          CACHES=$(echo "$IMAGES" | jq '. | {java}')
          bin/output.sh caches "$CACHES" >>$GITHUB_OUTPUT
          bin/output.sh images "$IMAGES" >>$GITHUB_OUTPUT
          cat "$GITHUB_OUTPUT"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: preflight
          path: preflight
          retention-days: 1

  # build-caches:
  #   needs: preflight
  #   strategy:
  #     matrix: ${{ fromJson(needs.preflight.outputs.caches) }}
  #   uses: ./.github/workflows/build-cache.yml
  #   with:
  #     JAVA_VERSION: ${{ matrix.java }}

  # build-images:
  #   needs:
  #     - preflight
  #     - build-caches
  #   strategy:
  #     matrix: ${{ fromJson(needs.preflight.outputs.images) }}
  #   uses: ./.github/workflows/build-image.yml
  #   with:
  #     JAVA_VERSION: ${{ matrix.java }}
  #     NODE_VERSION: ${{ matrix.node }}
  #     TAG: ${{ matrix.tag }}
  #   secrets: inherit

  save-preflight:
    # needs: build-images
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: preflight
          path: preflight
      - name: Commit and Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add preflight
          git status
          git commit -m "Update preflight" && git push || echo "No changes to commit"
